name: CI / Check
on:
  workflow_call:
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --no-install-recommends -y clang-format-15
      - run: CLANG_FORMAT_EXE=clang-format-15 ./scripts/check_format.sh
